# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Motthi's Website
author: Motthi
image: "/resource/img/ARLISS_TUS.jpg"
avatar: /resource/img/ARLISS_TUS.jpg
email: k11000660@gmail.com
description: ISASで惑星探査ローバについて研究している修士の学生
type: website
baseurl: ""
url: "https://motthi.github.io"
twitter_username: Motthi20
github_username: Motthi
timezone: Asia/Tokyo
google_analytics: G-4G4NFKNZMV
lang: "ja"
excerpt_separator: <!--more-->

header:
  links: # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

gems:
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
